# Generated by Django 5.0.3 on 2026-07-23 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Service Name')),
                ('service_type', models.CharField(choices=[('aggregator', 'Data Aggregation Service'), ('exporter', 'Export Service'), ('monitoring', 'System Monitoring Service'), ('reporting', 'Report Generation Service')], default='aggregator', max_length=50, verbose_name='Service Type')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('maintenance', 'Maintenance')], default='healthy', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Response Time (ms)')),
                ('error_rate', models.FloatField(default=0.0, verbose_name='Error Rate (%)')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run Time')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Analytics Service',
                'verbose_name_plural': 'Analytics Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Report Title')),
                ('report_type', models.CharField(choices=[('task_summary', 'Task Summary Report'), ('project_status', 'Project Status Report'), ('user_productivity', 'User Productivity Report'), ('sprint_velocity', 'Sprint Velocity Report'), ('ticket_resolution', 'Ticket Resolution Report'), ('custom', 'Custom Analytical Report')], default='task_summary', max_length=50, verbose_name='Report Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Report Parameters')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Computed Report Data')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
