# Generated by Django 5.0.3 on 2026-07-16 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workspace', '0002_remove_attachment_content_object'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('assign', 'Assigned'), ('status_change', 'Status Changed'), ('comment', 'Commented'), ('mention', 'Mentioned'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('upload', 'Uploaded File'), ('download', 'Downloaded File'), ('share', 'Shared'), ('archive', 'Archived'), ('restore', 'Restored')], max_length=20, verbose_name='Action Type')),
                ('action_description', models.TextField(verbose_name='Action Description')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Name')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Representation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Request Method')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Request Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='workspace.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='collaborati_actor_i_1da46c_idx'), models.Index(fields=['action_type'], name='collaborati_action__4c8c68_idx'), models.Index(fields=['content_type', 'object_id'], name='collaborati_content_e15241_idx'), models.Index(fields=['created_at'], name='collaborati_created_be950b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('content', models.TextField(verbose_name='Comment Content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comments/attachments/%Y/%m/%d/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.comment', verbose_name='Parent Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='collaborati_content_b8db01_idx'), models.Index(fields=['created_at'], name='collaborati_created_440eed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('context_url', models.URLField(blank=True, null=True, verbose_name='Context URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('mentioned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_given', to=settings.AUTH_USER_MODEL, verbose_name='Mentioned By')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL, verbose_name='Mentioned User')),
            ],
            options={
                'verbose_name': 'Mention',
                'verbose_name_plural': 'Mentions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='collaborati_content_b5c6f1_idx'), models.Index(fields=['mentioned_user', 'is_read'], name='collaborati_mention_3bedda_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'New Comment'), ('mention', 'Mention'), ('task_assigned', 'Task Assigned'), ('task_status', 'Task Status Changed'), ('ticket_created', 'New Ticket'), ('ticket_resolved', 'Ticket Resolved'), ('project_created', 'New Project'), ('project_completed', 'Project Completed'), ('team_added', 'Added to Team'), ('role_changed', 'Role Changed'), ('deadline_approaching', 'Deadline Approaching'), ('system', 'System Notification')], max_length=30, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='Action URL')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='collaborati_recipie_efaf98_idx'), models.Index(fields=['created_at'], name='collaborati_created_8a4bb0_idx'), models.Index(fields=['recipient', 'created_at'], name='collaborati_recipie_ca238e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('laugh', '😂 Laugh'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('wow', '😮 Wow'), ('applause', '👏 Applause'), ('thumbs_down', '👎 Dislike'), ('rocket', '🚀 Rocket'), ('fire', '🔥 Fire')], max_length=20, verbose_name='Reaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='collaborati_content_8a20be_idx'), models.Index(fields=['user'], name='collaborati_user_id_ee1cd4_idx')],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
