# Generated by Django 5.0.3 on 2026-07-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_object',
        ),
    ]
