# Generated by Django 5.0.3 on 2026-07-16 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('project', 'Project Chat'), ('team', 'Team Chat'), ('channel', 'Channel')], default='direct', max_length=20, verbose_name='Room Type')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Room Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('room_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Room ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat/avatars/%Y/%m/', verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Message At')),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Admins')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20, verbose_name='Role')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Is Muted')),
                ('muted_until', models.DateTimeField(blank=True, null=True, verbose_name='Muted Until')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Read At')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_members', to='communication.chatroom', verbose_name='Chat Room')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat Room Member',
                'verbose_name_plural': 'Chat Room Members',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', through='communication.ChatRoomMember', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Message ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('system', 'System Message'), ('notification', 'Notification')], default='text', max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is Edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('is_system', models.BooleanField(default=False, verbose_name='Is System Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.chatroom', verbose_name='Chat Room')),
                ('delivered_to', models.ManyToManyField(blank=True, related_name='delivered_messages', to=settings.AUTH_USER_MODEL, verbose_name='Delivered To')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communication.message', verbose_name='Parent Message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by_members', to='communication.message', verbose_name='Last Read Message'),
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, verbose_name='Delivered At')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read', to='communication.message', verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Message Read',
                'verbose_name_plural': 'Message Reads',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline'), ('dnd', 'Do Not Disturb')], default='offline', max_length=20, verbose_name='Status')),
                ('custom_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Status')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('devices', models.JSONField(blank=True, default=list, verbose_name='Devices')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', 'is_active'], name='communicati_room_ty_5b5a50_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['content_type', 'object_id'], name='communicati_content_b9e08d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_message_at'], name='communicati_last_me_3425bb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_id'], name='communicati_room_id_9ca7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'created_at'], name='communicati_chat_ro_780abe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='communicati_sender__9b3871_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_id'], name='communicati_message_84ae99_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='communicati_is_dele_2a9cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['parent_message'], name='communicati_parent__05d79b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['message', 'user'], name='communicati_message_787a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['is_read'], name='communicati_is_read_46ed63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['status'], name='communicati_status_4c4456_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['last_activity'], name='communicati_last_ac_1b4924_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['user', 'status'], name='communicati_user_id_f47b50_idx'),
        ),
    ]
